### PR TITLE
Fix for removed methods in Bukkit 1.12

### PR DESCRIPTION
**Pull request by lucko**
`YamlConfiguration#loadConfiguration(InputStream)` was removed in this Bukkit commit, preventing mcMMO from loading on 1.12.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/f2a9b248754b4fd91c0ae69d659a8bbf64ed4929

### CODE REVIEW

**Comment by Sikatsu** [comment]
When hitting mobs instead of hearts this shows up: http://prntscr.com/fa5369

**Comment by lucko** [comment]
I don't see how that's related to this PR?

**Comment by Sikatsu** [comment]
Don't know. But seems thats broken on 1.12 aswell? Just reported it.

Op zo 21 mei 2017 11:00 schreef Luck <notifications@github.com>:

**Comment by lucko** [comment]
Make an issue for it then.

**Pull request merged**
