### PR TITLE
enhancement: Make unarmed ironarm damage configurable in multiple ways

### PR DESCRIPTION
**Pull request by CollinHerber**

### CODE REVIEW

**Comment by CollinHerber** [comment]
Solves https://github.com/mcMMO-Dev/mcMMO/issues/3983

**Comment by nossr50** [comment]
I don't agree with these changes, more or less I'd like to keep it in a rank based system. That is the reason for closing this PR.

**Comment by CollinHerber** [comment]
@nossr50 There is a configurable option for using the ranking system. You could make that true by default should you so choose. Don't think it warrants a full close though.

**Comment by nossr50** [comment]
I would rather that not be an option. You can come talk to me about it in discord to understand my thought process, but I'm not going to accept a PR just because you have good intentions.

I plan to make everything configurable, but I don't plan to make the rank system optional at this moment in time.

**Pull request closed without merging**
