### PR TITLE
Fix 3250

### PR DESCRIPTION
**Pull request by ezeiger92**
Fix for issue #3250, changed HashSet<Byte> to HashSet<Material> for calls to getTargetBlock.

### CODE REVIEW

**Comment by SXRWahrheit** [comment]
Could you put a compiled version of this on Drive or something? Would really like to stop the error spam on my server before @t00thpick1 or @TfT-02 pull this :)

**Comment by ezeiger92** [comment]
I'm lazy so here's the build we're using: it also fixes #3249 and #3251
Had to zip because github doesn't like jars in here
[mcMMO.zip](https://github.com/mcMMO-Dev/mcMMO/files/1209745/mcMMO.zip)

**Comment by SXRWahrheit** [comment]
Great, thanks!

**Comment by ezeiger92** [comment]
Just updated the zip because really stupid stuff with ice fishing

**Comment by SXRWahrheit** [comment]
Does your new zip fix the Kraken? I was using your zip and still not getting Kraken.

**Pull request merged**
