### PR TITLE
Add PartyCreated and PartyDisbanded events

### PR DESCRIPTION
**Pull request by GaetanRAYNAUD**

### CODE REVIEW

**Comment by electronicboy** [comment]
events are in the wrong place to be able to handle cancellation, not that you even handle that?

**Comment by GaetanRAYNAUD** [comment]
> events are in the wrong place to be able to handle cancellation, not that you even handle that?

My idea is get the events after the party is created/disbanded, so putting them before would not allow me to do that.
But for sure I need to undo creation/disbanding of the party if the event is canceled. Or do you want me to send the event before and prevent if that append ?

**Comment by electronicboy** [comment]
prevention is better then having to track everything that you just did and undo it, especially for things like disbanding

Worth noting that all events are going to be replaced/deprecated in 2.2, so not entirely 100% sure on if we should be adding more events at this phase either, but 2.2 is still a WIP....

**Comment by GaetanRAYNAUD** [comment]
Ok, this request can be closed.
I'll wait for 2.2 and see what's inside.

**Pull request closed without merging**
