### PR TITLE
Update locale_it.properties

### PR DESCRIPTION
**Pull request by Fabrimat**
Fixed definetly /mctop and fixed special characters.

### CODE REVIEW

**Comment by adamxp12** [comment]
Can one of the admins verify this patch?

**Comment by Draycia** [comment]
Please don't comment on every single PR asking for it to be verified.
Noss or another dev will look at the PRs when they have time to.

**Comment by adamxp12** [comment]
That comment was not by me? I havent been on github today... and the is no sessions other than the computer I am on inside github settings. and I have 2fa and everything. very confused. I have nothing to do with this patch

**Comment by Draycia** [comment]
You've authorized something with your account, probably a jenkins plugin, to automatically say that.

https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

"When a new pull request is opened in the project and the author of the pull request isn't white-listed, builder will ask "Can one of the admins verify this patch?"."

**Pull request merged**
