### PR TITLE
Added 1.13 to 1.17 mob loot to shake

### PR DESCRIPTION
**Pull request by dodieboy**
This PR added support for 1.13 to 1.17 mob to fishing skill shake. I did not add Ravager as it only drop saddle and i think it may be too broken if a player can easily get saddle with it, how do you all think?

### CODE REVIEW

**Comment by Axyzel** [comment]
Not sure ravager would be that broken, especially if there's a way to only get one from it. You can already get copious amounts of saddles from normal fishing.

**Comment by dodieboy** [comment]
from what i see how the shake work, if the mob only have 1 item drop, it will get the item 100% of the time when shake activate. So a player can get like about 40 saddle if you are lucky on max fishing level

**Comment by dodieboy** [comment]
Did some test if my shake is 30% i can get 11 saddle from 1 ravager

**Comment by dodieboy** [comment]
Tried to add tipped arrow to stray but the potion effect is not applying to the item, did I did anything wrong?

image

**Comment by Axyzel** [comment]
Point taken on the ravager. Saddles aren't mega useful but that is kinda ridiculous, at high level that's more powerful than a raid farm.
On the note of the stray, you may be using the wrong metadata tags for the kind of potion? It might just be Potion not PotionType. Not certain but that's probably where the issue is?

**Comment by dodieboy** [comment]
If mcmmo is using the naming from spigot I believe the effect should be "SLOWNESS" and I believe it is in the "PotionData" base on the spigot api and the potion for witch in this config file is also using "PotionData"

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html

**Comment by gecko10000** [comment]
Compatibility for all pre-1.17.1 versions was removed with the most recent update, so I don't see how this will help with anything.

**Comment by dodieboy** [comment]
All mob from pre1.17.1 will still be in 1.17.1, how does this PR not help in anything?

**Comment by gecko10000** [comment]
Sorry, I thought you meant you were adding support for each version, not the new mobs. My bad.

**Pull request closed without merging**
